version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:80
    environment:
      - NODE_ENV=production

      - APP_FORM_KEY=FILES
      - APP_MORGAN_LOG_FORMAT=combined
      - APP_MAX_FILE_SIZE=26214400
      - APP_MAX_FILES_NUMBER=5

      - CLAMD_IP=clamav
      - CLAMD_PORT=3310
      - CLAMD_TIMEOUT=30000